apiVersion: apps/v1
kind: Deployment
metadata:
  name: pl-stats-frontend
  labels:
    app: pl-stats-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pl-stats-frontend
  template:
    metadata:
      labels:
        app: pl-stats-frontend
    spec:
      containers:
        - name: frontend
          image: plstatsacr.azurecr.io/pl-stats-frontend:v2
          ports:
            - containerPort: 3000
          env:
            - name: AGENT_URL
              value: "http://pl-stats-agent-svc:8000"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10